name: Docker Image CI

on:
  push:
    branches: [ "philibus/CI" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_REPO }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  pull_image_restart_container:
    name: Pull docker image and restart container
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Login to server and run commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USER }}
          password: ${{ secrets.REMOTE_DEV_PASSWORD }}
          script: |
            cd ${{ secrets.REMOTE_DEV_COMPOSE_LOCATION }} &&
            docker compose -f ${{ secrets.REMOTE_DEV_COMPOSE_FILENAME }} down &&
            docker compose -f ${{ secrets.REMOTE_DEV_COMPOSE_FILENAME }} pull &&
            docker compose -f ${{ secrets.REMOTE_DEV_COMPOSE_FILENAME }} up -d

